### ISSUE TITLE
Installing on macOS

### ISSUE THREAD

**Issue by janithwanni** [clips/wordkit#14]
I believe there is a small issue with dependencies as I met with an error about a module named ipapy which went along the lines of 
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 1331: ordinal not in range(128)`

I went and checked with the ipapy repo and it seemed that the issue was fixed in a recent pull request. is wordkit using an older version of ipapy?

**Comment by stephantul** [comment]
Hey @janithwanni,

The bug has been fixed, but the fix unfortunately has not been pushed to `pypi` yet.
Otherwise, we use the most recent version.
I opened an issue on the `ipapy` repo (see [here](https://github.com/pettarin/ipapy/issues/3)), asking them to push to `pypi`, but that has not happened yet. 

As far as I know, the only way to fix this is to install `ipapy` from source, which should be painless (e.g. just clone the repo and run `setup.py install`, as usual). A bit of an unfortunate hassle, but there is nothing we can do about this right now (except maybe packaging `ipapy` with wordkit, but I'm not really willing to do this right now.)

I don't get this error on linux or macOS, using python 3.4 >=. Could you let me know what version of python you are using? I thought this bug only affected Windows users.

Stéphan

**Comment by janithwanni** [comment]
Hi @stephantul,
I'm using python 3.5.4 in macOS Mojave. Yes, it later dawned on me that I should just clone the source and install and it did the trick. 😅 
Thanks a lot! 😃
